// lib/pages/agp001.dart
// Converted from WML: agp001.wml
//
// Generated by TWapFlutterWriter
// Date:      2026-07-17
// GENERATOR: 2026-07-16 r19          <- wapflutter.pas
// TEMPLATE:  2026-07-16 r19      <- flutter.tpl
// （兩行版本要一致；不一致表示有一邊沒換到）
//
// WML → 模組對照：
//   <dbquery id=>              → TSQLQuery + DataSetRegistry（dbquery()）
//   <field>                   → persistent field fkData（_fld / _key）
//   <dbtable>                 → persistent field fkLookup（_lkp）
//   <field value="運算式">      → persistent field fkCalculated（_cal）+ onCalcFields
//   <onevent type=...>        → TDataSet.onNewRecord / beforePost / beforeDelete /
//                               beforeEdit / beforeInsert / afterPost / afterDelete /
//                               afterScroll
//   <function id=>            → Dart method
//   <datasource> + <navigator> → TDataSource + TDBNavigator
//   <dbgrid><item>            → TDBGrid + TDBGridColumns
//   <input field= [lookup=]>  → TDBEdit / WapLookupBox
//   <setvar>/<if>/<while>/<invoke>/<exit>/<alert>/<log> → 引擎原樣（setvar/condition/invoke）

import 'package:flutter/material.dart';
import 'package:wapform_flutter/wapform_flutter.dart';

// ══════════════════════════════════════════════════════════════════
//  資料庫連線
// ══════════════════════════════════════════════════════════════════
const String _kDb = 'WapProductionDB';

TWapSQLConnection? _wapConn;
TWapSQLConnection _conn() {
  if (_wapConn == null) {
    final c = TWapSQLConnection(null, const WapDbBridgeDriver());
    c.databaseName = _kDb;
    final tx = TSQLTransaction();
    tx.database = c; // 自動掛成 c.transaction
    _wapConn = c;
  }
  return _wapConn!;
}

// ══════════════════════════════════════════════════════════════════
//  persistent fields 建構 helper
//  LCL 標準：欄位建立時 dataSet:=q 即註冊進 q.Fields。
//  Fields 順序 ＝ WML <field> 順序 ＝ DBGrid 未指定 columns 時的顯示順序。
//  存檔：TSQLQuery.applyUpdates 由 SQL 抽表名、由 pfInKey 欄組 WHERE。
// ══════════════════════════════════════════════════════════════════
TField _fieldOf(String type) {
  switch (type) {
    case 'integer':
      return TIntegerField();
    case 'float':
    case 'currency':
      return TFloatField();
    case 'date':
    case 'datetime':
    case 'time':
      return TDateTimeField();
    case 'boolean':
      return TBooleanField();
    default:
      return TStringField();
  }
}

// 日期欄在 WML 常沒寫 type，建出來是字串欄，值是 "2021-01-29T16:00:00"。
// onGetText 只攔「顯示」，截掉時間；存檔／運算式取值保留完整原始值。
void _setDateOnlyText(TField f) {
  f.onGetText = (fld, ref, displayText) {
    final raw = fld.value;
    final s = raw == null ? '' : "$raw";
    if (!displayText) {
      ref.value = s;
      return;
    }
    final t = s.indexOf("T");
    final sp = s.indexOf(" ");
    var cut = -1;
    if (t >= 0) cut = t;
    if (sp >= 0 && (cut < 0 || sp < cut)) cut = sp;
    ref.value = cut > 0 ? s.substring(0, cut) : s;
  };
}

// <field fieldname= displaylabel= [type=]/>
void _fld(TSQLQuery q, String name, String label,
    {String type = '', bool dateOnly = false}) {
  final f = _fieldOf(type);
  f.fieldName = name;
  f.fieldKind = TFieldKind.fkData;
  if (label != '') f.displayLabel = label;
  if (dateOnly) _setDateOnlyText(f);
  f.dataSet = q;
}

// key 欄：pfInKey → applyUpdates 的 UPDATE/DELETE WHERE 用它
void _key(TSQLQuery q, String name, String label,
    {String type = '', bool dateOnly = false}) {
  final f = _fieldOf(type);
  f.fieldName = name;
  f.fieldKind = TFieldKind.fkData;
  f.providerFlags = {
    TProviderFlag.pfInKey,
    TProviderFlag.pfInUpdate,
    TProviderFlag.pfInWhere,
  };
  if (label != '') f.displayLabel = label;
  if (dateOnly) _setDateOnlyText(f);
  f.dataSet = q;
}

// <dbtable [name=] tablename= keyfields= lookupkeyfields=><field [name=] fieldname=>
void _lkp(TSQLQuery q, String name, String label,
    {required String keyField,
    required String lookupKey,
    required String resultField,
    required TDataSet lookupDs,
    String type = '',
    bool dateOnly = false}) {
  final f = _fieldOf(type);
  f.fieldName = name;
  f.fieldKind = TFieldKind.fkLookup;
  f.keyFields = keyField;
  f.lookupDataSet = lookupDs;
  f.lookupKeyFields = lookupKey;
  f.lookupResultField = resultField;
  f.lookupCache = false;
  f.providerFlags = {}; // lookup 欄不參與 INSERT/UPDATE
  if (label != '') f.displayLabel = label;
  if (dateOnly) _setDateOnlyText(f);
  f.dataSet = q;
}

// <field ... value="運算式"/>：求值在 onCalcFields
void _cal(TSQLQuery q, String name, String label, {String type = 'integer'}) {
  final f = _fieldOf(type);
  f.fieldName = name;
  f.fieldKind = TFieldKind.fkCalculated;
  f.providerFlags = {}; // calc 欄不參與 INSERT/UPDATE
  if (label != '') f.displayLabel = label;
  f.dataSet = q;
}

// ══════════════════════════════════════════════════════════════════
//  資料集操作 helper
// ══════════════════════════════════════════════════════════════════
String _str(TDataSet ds, String name) => ds.findField(name)?.asString ?? '';

Future<void> _saveAsync(TSQLQuery q) async {
  if (dsEditModes.contains(q.state)) q.post();
  await q.applyUpdatesAsync();
}

Future<void> _delAsync(TSQLQuery q) async {
  q.delete();
  await q.applyUpdatesAsync();
}

// <dbquery> 沒有 id 的（純 DML）
Future<void> _execSql(String sql) async {
  final q = TSQLQuery();
  q.database = _conn();
  q.sql.text = sql;
  await q.execSQLAsync();
  q.free();
}

// ══════════════════════════════════════════════════════════════════
//  版面常數 / helper
// ══════════════════════════════════════════════════════════════════
const _kBlue   = Color(0xFF1A6FB5);
const _kBorder = Color(0xFFD3D1C7);

const double _kChar = 8.0; // WML size=字元數 → 像素
double _w(num size) => size * _kChar;

// <dbgrid><item field= size=/> → TColumn
TColumn _column(TDBGridColumns cols, String f, String cap, num size,
    {bool ro = false, TAlignment align = TAlignment.taLeftJustify}) {
  final c = cols.add();
  c.fieldName = f;
  c.width = _w(size).round();
  c.readOnly = ro;
  c.alignment = align;
  c.title.caption = cap;
  return c;
}

// ══════════════════════════════════════════════════════════════════
//  card P — 系統參數建檔
// ══════════════════════════════════════════════════════════════════
void showAgp001(BuildContext context) => showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Agp001CardP(),
    );

class Agp001CardP extends StatefulWidget {
  // @@@ 子卡要看得到父卡的變數與資料集（例如報表卡的 SQL 用 $C/$D，
  //     那是上一張卡 <input name="C"> 的值）→ ev/reg 由開卡的人傳進來。
  final WapEvaluator? ev;
  final DataSetRegistry? reg;
  const Agp001CardP({super.key, this.ev, this.reg});
  @override
  State<Agp001CardP> createState() =>
      _Agp001CardPState();
}

class _Agp001CardPState
    extends State<Agp001CardP> {
  late final WapEvaluator _ev = widget.ev ?? WapEvaluator();
  late final DataSetRegistry _reg = widget.reg ?? DataSetRegistry();
  bool get _ownsReg => widget.reg == null;

  // ── <dbquery id="..."> 物件列 ────────────────────────────────────
  //  第一次    → 新建、掛連線、登錄進 registry，並跑 define（建欄位）
  //  第二次以上 → 沿用同一物件（欄位定義／UI 綁定全保住），只換 SQL
  TSQLQuery dbquery(String id, String sqlText,
      {void Function(TSQLQuery ds)? define}) {
    final existing = _reg.find(id);
    TSQLQuery q;
    var isNew = false;
    if (existing is TSQLQuery) {
      q = existing;
    } else {
      q = TSQLQuery();
      q.database = _conn();
      q.name = id;
      _reg.put(id, q);
      isNew = true;
    }
    if (sqlText.isNotEmpty) {
      final sql = expandSql(sqlText); // 展開 $變數
      if (q.active) q.close();
      q.unPrepare();
      q.sql.text = sql;
    }
    q.alwaysUpdateable = true;
    if (isNew && define != null) define(q);
    return q;
  }

  // ══ 資料集 ══════════════════════════════════════════════════════
  // [diag] ds "sys": foreign=0 declared=1 lookupSrc=0 fields=18
  // <dbquery id="sys">select * from sys
  late final TSQLQuery _sys =
      dbquery("sys", r"select * from sys", define: (ds) {
    _fld(ds, "No", "No");
    _fld(ds, "Company", "公司名稱");
    _fld(ds, "Addr", "公司地址");
    _fld(ds, "AC", "統一編號");
    _fld(ds, "Zip", "郵遞區號");
    _fld(ds, "Phone", "電話");
    _fld(ds, "FAX", "傳真");
    _fld(ds, "TaxRate", "稅率");
    _fld(ds, "Printer1", "Printer1");
    _fld(ds, "Printer2", "Printer2");
    _fld(ds, "Printer3", "Printer3");
    _fld(ds, "Design", "列印表尾");
    _fld(ds, "AcBeg", "結帳日起");
    _fld(ds, "AcEnd", "結帳日訖");
    _fld(ds, "Rem", "訂單備註");
    _fld(ds, "New", "最新動態");
    _fld(ds, "sales", "促銷方案");
    _fld(ds, "a2500", "贈品選項");

  });

  // ══ DataSource ═════════════════════════════════════════════════
  late final TDataSource _sysSrc;

  // ══ dbgrid 欄位 ════════════════════════════════════════════════

  bool   _loading = true;
  String _error   = '';

  @override
  void initState() {
    super.initState();
    _conn();

    _sysSrc = TDataSource()..dataSet = _sys;
    _bindEngine();
    // ── card 開場的 <setvar> ──

    _load();
  }

  @override
  void dispose() {
    for (final c in _varCtls.values) {
      c.dispose();
    }
    if (_ownsReg) {   // 不是自己建的 registry 就不能 free，會殺掉父卡的資料集
    _sysSrc.dataSet = null; // LCL TDataSource 無 dispose
    _sys.free();
      _reg.releaseAll();
    }
    super.dispose();
  }

  // 綁引擎 + 觸發 late final 建構（讓所有資料集都進 registry）
  void _bindEngine() {
    useEngine(_ev, _reg);
    _reg.put("sys", _sys);
  }

  Future<void> _load() async {
    if (mounted) setState(() { _loading = true; _error = ''; });
    try {
      // lookup 來源表：失敗不中斷主流程
      for (final id in []) {
        try {
          final ds = _reg.findQuery(id)!;
          await dbquery(id, ds.sql.text).openAsync();
        } catch (e) {
          debugPrint("[agp001] $id skip: $e");
        }
      }
      await dbquery("sys", r"select * from sys").openAsync();
    } catch (e, st) {
      debugPrint("[agp001] _load ERROR: $e\n$st");
      if (mounted) setState(() => _error = e.toString());
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  // <onevent type="onnewrecord"> 的 SQL 前置。
  // @@@ TDBNavigator：onInsertAsync 會「取代」ds.insert()，不是在它之前跑
  //     （lazarus_dbctrls.dart nbInsert）。所以這裡必須自己呼叫 insert()。
  Future<void> _sysInsert() async {
    try {
      _sys.insert(); // → 觸發 onNewRecord
      if (mounted) setState(() {});
    } catch (e) {
      _snack("新增失敗：$e");
    }
  }

  // navigator Post（beforePost 由 TDataSet 自己觸發）
  Future<void> _sysPost() async {
    try {
      await _saveAsync(_sys);
      _snack("已儲存", ok: true);
      if (mounted) setState(() {});
    } catch (e) {
      _snack("儲存失敗：$e");
    }
  }

  // <onevent type="beforedelete">
  Future<void> _sysDelete() async {
    try {
      await _delAsync(_sys);
      _snack("已刪除", ok: true);
      if (mounted) setState(() {});
    } catch (e) {
      _snack("刪除失敗：$e");
    }
  }

  // ══ UI helper ══════════════════════════════════════════════════
  void _snack(String msg, {bool ok = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(msg),
      backgroundColor: ok ? Colors.green.shade700 : Colors.red.shade700,
      duration: const Duration(seconds: 2),
    ));
  }

  // <alert message="..."/>
  void _alert(String msg) {
    if (!mounted) return;
    showDialog(
      context: context,
      builder: (c) => AlertDialog(
        shape: const RoundedRectangleBorder(borderRadius: BorderRadius.zero), // @@@ 直角外框
        content: Text(msg),
        actions: [
          TextButton(
              onPressed: () => Navigator.of(c).pop(), child: const Text("確定")),
        ],
      ),
    );
  }

  // <log message="..."/>
  void _log(String msg) => debugPrint("[agp001][log] $msg");

  // <td> 內的一行（以 <br/> 分行）
  Widget _line(List<Widget> children) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 2),
        child: Row(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: children),
      );

  // <td> 內的文字節點
  Widget _lbl(String s) => Padding(
        padding: const EdgeInsets.only(right: 2),
        child: Text(s, style: const TextStyle(fontSize: 13)),
      );
  // @@@ 右對齊定寬 label（fieldset 表單：label 靠右、輸入靠左，各列輸入對齊同一 x）
  Widget _lblR(String s, double w) => SizedBox(
        width: w,
        child: Padding(
          padding: const EdgeInsets.only(right: 6),
          child: Align(
            alignment: Alignment.centerRight,
            child: Text(s, style: const TextStyle(fontSize: 13)),
          ),
        ),
      );

  // <td [_]width="...">
  Widget _td(double width, List<Widget> children) => SizedBox(
        width: width,
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: children),
      );

  // <input field="..." size="..." [readonly] [type="memo"]/>
  Widget _edit(TDataSource src, String field, num size,
      {bool ro = false,
      bool memo = false,
      double order = 0,
      FocusNode? focusNode,
// aa ### flutter 擴充
      // autofocus：進畫面游標停在這一格（WML 沒有這個概念，Flutter 要明指）。
      bool autofocus = false,
      // roFocusable：唯讀但仍納入 Tab 順序 —— 例如「銷貨單號」是唯讀的，
      // 但使用者按 Tab 時仍要能停上去再跳到下一格。
      // Flutter 的唯讀欄預設會被 ExcludeFocusTraversal 排除，LCL 沒這回事。
      bool roFocusable = false}) {
// zz ### flutter 擴充
    Widget e = SizedBox(
      width: _w(size) < 44 ? 44.0 : _w(size), // @@@ 最小可用寬（size 太小的欄位也點得進、輸入得了，如稅率 size=2）
      height: memo ? 56 : 26,
      child: TDBEdit(
        dataSource: src,
        dataField: field,
        readOnly: ro,
        focusNode: focusNode,
        autofocus: autofocus,
        font: const TextStyle(fontSize: 13),
      ),
    );
    if (ro && !roFocusable) {
      return ExcludeFocusTraversal(child: e); // 唯讀欄不納入 Tab
    }
    if (order > 0) {
      e = FocusTraversalOrder(order: NumericFocusOrder(order), child: e);
    }
    return e;
  }

  // <input field="..." lookup="dataset;keyfield;displayfield"/>
  Widget _lookupBox(TSQLQuery own, TSQLQuery lk, String field, num size,
      String keyField, List<String> displayFields,
      {double order = 0, Future<void> Function(String key)? onPicked}) {
    Widget b = SizedBox(
      width: _w(size),
      height: 28,
      child: WapLookupBox(
        value: _str(own, field),
        width: _w(size),
        dataSet: lk,
        keyField: keyField,
        displayFields: displayFields,
        colWidths: List<double>.filled(displayFields.length, 160),
        onChanged: (key) async {
          if (onPicked != null) {
            await onPicked(key);
            return;
          }
          if (own.state == TDataSetState.dsBrowse) own.edit();
          final v = key.replaceAll("'", "''");
          setvar("${own.name}.$field", "'$v'");
          own.dataEvent(TDataEvent.deRecordChange, 0); // 重算 fkLookup 欄
          if (mounted) setState(() {});
        },
      ),
    );
    if (order > 0) {
      b = FocusTraversalOrder(order: NumericFocusOrder(order), child: b);
    }
    return b;
  }

  // ── <input name="X" value="$_X"/>：綁「引擎變數」而不是資料集欄位 ──
  //  對應舊 wap_tag 的具名 input。值進 WapEvaluator 的變數表，
  //  <function> 裡的 setvar/condition 才讀得到。
  final Map<String, TextEditingController> _varCtls = {};

  // 把字串當「常值」寫進引擎變數（setvar 的 value 是運算式，要包單引號）
  void _setVarStr(String name, String v) {
    final e = v.replaceAll("'", "''");
    setvar(name, "'$e'");
  }

  TextEditingController _varCtl(String name, String init) =>
      _varCtls.putIfAbsent(name, () {
        var v = '';
        try {
          v = expression(init).toString();
        } catch (_) {}
        if (v == 'null') v = '';
        _setVarStr(name, v);
        final c = TextEditingController(text: v);
        c.addListener(() => _setVarStr(name, c.text));
        return c;
      });

  // <input name= value= [type="date"] size=/>
  // @@@ 內容自適應：寬度跟著目前文字長度縮放，下限 max(size×字元寬,44)、
  //     上限 max(size×字元寬×2,120)，打字變長即時長大；高度自動（isDense 撐單行）。
  Widget _vedit(String name, String init, num size, {double order = 0}) {
    final ctl = _varCtl(name, init);
    final base = size * _kChar;
    final minW = base < 44 ? 44.0 : base.toDouble();
    final maxW = (base * 2) < 120 ? 120.0 : (base * 2).toDouble();
    final w = ((ctl.text.length + 2) * _kChar).clamp(minW, maxW).toDouble();
    Widget e = SizedBox(
      width: w,
      child: TextField(
        controller: ctl,
        onChanged: (_) {
          if (mounted) setState(() {}); // 內容變 → 重算寬度
        },
        style: const TextStyle(fontSize: 13),
        decoration: const InputDecoration(
            isDense: true,
            contentPadding: EdgeInsets.symmetric(horizontal: 6, vertical: 6),
            border: OutlineInputBorder()),
      ),
    );
    if (order > 0) {
      e = FocusTraversalOrder(order: NumericFocusOrder(order), child: e);
    }
    return e;
  }

  // <input type="checkbox" name= value=/>
  Widget _vcheck(String name, String onValue) {
    final on = _str2(name) == onValue;
    return SizedBox(
      width: 30,
      height: 26,
      child: Checkbox(
        value: on,
        onChanged: (v) {
          setvar(name, (v ?? false) ? "'$onValue'" : "''");
          if (mounted) setState(() {});
        },
      ),
    );
  }

  // <input name= value= lookup="ds;key;disp"/>
  Widget _vlookup(String name, String init, TSQLQuery lk, num size,
      String keyField, List<String> displayFields, {double order = 0}) {
    _varCtl(name, init); // 確保變數有初值
    Widget b = SizedBox(
      width: _w(size),
      height: 28,
      child: WapLookupBox(
        value: _str2(name),
        width: _w(size),
        dataSet: lk,
        keyField: keyField,
        displayFields: displayFields,
        colWidths: List<double>.filled(displayFields.length, 160),
        onChanged: (key) {
          _setVarStr(name, key);
          _varCtls[name]?.text = key;
          if (mounted) setState(() {});
        },
      ),
    );
    if (order > 0) {
      b = FocusTraversalOrder(order: NumericFocusOrder(order), child: b);
    }
    return b;
  }

  // <refresh> —— 變數被 setvar 改過之後，把畫面上的 input 重新讀回來
  void _refreshVars() {
    for (final e in _varCtls.entries) {
      final v = _ev.getVar(e.key);
      e.value.text = (v == null) ? '' : "$v";
    }
    if (mounted) setState(() {});
  }

  // 讀引擎變數的字串值
  String _str2(String name) {
    final v = _ev.getVar(name);
    return (v == null) ? '' : "$v";
  }

  // <pagecontrol><tabsheet caption="..."> 的一頁
  Widget _tabPage(List<Widget> children) => SingleChildScrollView(
        padding: const EdgeInsets.all(4),
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: children),
      );

  // <p align="center"><navigator/></p>
  Widget _nav(TDataSource src,
          {Future<void> Function()? post,
          Future<void> Function()? insert,
          Future<void> Function()? del}) =>
      Center(
        child: TDBNavigator(
          dataSource: src,
          onPostAsync: post,
          onInsertAsync: insert,
          onDeleteAsync: del,
        ),
      );

 // @@@ 無 navigator：離開前若在編輯狀態自動存檔
 Future<void> _saveIfEditing() async {
    await _saveAsync(_sys);
 }

  // ══ build ══════════════════════════════════════════════════════
  @override
  Widget build(BuildContext context) {
    return PopScope(
   canPop: false,
   onPopInvokedWithResult: (didPop, result) async {
    if (didPop) return;
    // 存檔失敗/例外/卡住也一定要能關閉（try + 5 秒逾時）
    try { await _saveIfEditing().timeout(const Duration(seconds: 5)); } catch (_) {}
    if (mounted) Navigator.of(context).pop();
   },
   child: Dialog(
      insetPadding: const EdgeInsets.all(12),
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.zero), // @@@ 直角外框
      child: ConstrainedBox(
        constraints: const BoxConstraints(maxWidth: 1180, maxHeight: 840),
        child: IntrinsicWidth(child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
          Container(

            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
            color: _kBlue,
            child: const Row(children: [
              Icon(Icons.article_outlined, color: Colors.white, size: 20),
              SizedBox(width: 8),
              Text('系統參數建檔',
                  style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w600)),
            ]),
          ),
          // @@@ Flexible(loose)：內容短就縮短（不再撐滿 maxHeight 留大片空白），
          //     內容多才到 maxHeight 後由內層 SingleChildScrollView 捲動。
          Flexible(
            fit: FlexFit.loose,
            child: _loading
                ? const Center(child: CircularProgressIndicator())
                : _error.isNotEmpty
                    ? Center(
                        child: Padding(
                          padding: const EdgeInsets.all(20),
                          child: Text("載入失敗：$_error",
                              style: const TextStyle(color: Colors.red)),
                        ),
                      )
                    : FocusTraversalGroup(
                        policy: OrderedTraversalPolicy(),
                        child: SingleChildScrollView(
                          padding: const EdgeInsets.all(10),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              // <datasource dataset="sys">
                                // [diag] fieldset children=48 dsId=sys foreign=False
                                  _line([
                                    _lblR("公司名稱:", 75.0),
                                    _edit(_sysSrc, "Company", 30, order: 1, autofocus: true),
                                  ]),
                                  _line([
                                    _lblR("公司地址:", 75.0),
                                    _edit(_sysSrc, "Addr", 40, order: 2),
                                  ]),
                                  _line([
                                    _lblR("統一編號:", 75.0),
                                    _edit(_sysSrc, "AC", 10, order: 3),
                                  ]),
                                  _line([
                                    _lblR("郵遞區號:", 75.0),
                                    _edit(_sysSrc, "Zip", 10, order: 4),
                                  ]),
                                  _line([
                                    _lblR("電話:", 75.0),
                                    _edit(_sysSrc, "Phone", 15, order: 5),
                                  ]),
                                  _line([
                                    _lblR("傳真:", 75.0),
                                    _edit(_sysSrc, "FAX", 15, order: 6),
                                  ]),
                                  _line([
                                    _lblR("稅率:", 75.0),
                                    _edit(_sysSrc, "TaxRate", 2, order: 7),
                                  ]),
                                  _line([
                                    _lblR("列表機-1:", 75.0),
                                    _edit(_sysSrc, "Printer1", 20, order: 8),
                                  ]),
                                  _line([
                                    _lblR("列表機-2:", 75.0),
                                    _edit(_sysSrc, "Printer2", 20, order: 9),
                                  ]),
                                  _line([
                                    _lblR("列表機-3:", 75.0),
                                    _edit(_sysSrc, "Printer3", 20, order: 10),
                                  ]),
                                  _line([
                                    _lblR("結帳日起:", 75.0),
                                    _edit(_sysSrc, "AcBeg", 8, order: 11),
                                  ]),
                                  _line([
                                    _lblR("結帳日訖:", 75.0),
                                    _edit(_sysSrc, "AcEnd", 8, order: 12),
                                  ]),
                                  _line([
                                    _lblR("訂單備註:", 75.0),
                                    _edit(_sysSrc, "Rem", 60, order: 13),
                                  ]),
                                  _line([
                                    _lblR("最新動態:", 75.0),
                                    _edit(_sysSrc, "New", 60, order: 14),
                                  ]),
                                  _line([
                                    _lblR("促銷方案:", 75.0),
                                    _edit(_sysSrc, "sales", 60, order: 15),
                                  ]),
                                  _line([
                                    _lblR("贈品選項:", 75.0),
                                    _edit(_sysSrc, "a2500", 60, order: 16),
                                  ]),
                              // </datasource sys>
                            ],
                          ),
                        ),
                      ),
          ),
          // ── <do> 按鈕列 ──
          Container(
            padding: const EdgeInsets.all(8),
            decoration: const BoxDecoration(
                border: Border(top: BorderSide(color: _kBorder))),
            child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
              // <do type="accept" label="mail">
              TButton(caption: "mail", onClick: () async {
                setvar("I", "0");
                setvar("S", "MD5(NOW)");
                _alert("aaa");
                // TODO <mail> 尚未支援（外部動作／報表輸出）
                _alert("bbb");
                if (mounted) setState(() {});
              }),
              const SizedBox(width: 8),
              // <do type="prev" label="關閉">
              TButton(caption: "關閉", onClick: () {
                Navigator.of(context).maybePop();
                if (mounted) setState(() {});
              }),
            ]),
          ),
        ]),)
      ),
    ));
  }
}
